Xbee:
  port: /dev/ttyUSB0
  node_id: "Node 0"
  timeout_receiver: 0.2

CADMM:
  init_y: [0,0] # if None then random initialization
  cost: "Affine"
  c: 0.5

Network:
  A: None  # if None then get from xbee neighbors